* Exercise 1 : Array Creation And Manipulation

In [2]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


* Exercise 2 : Type Conversion And Array Operations

In [3]:
import numpy as np

lst = [3.14, 2.17, 0, 1, 2]
arr = np.array(lst, dtype=int)
print(arr)

[3 2 0 1 2]


In [ ]:
 Exercise 3 : Working With Multi-Dimensional Arrays

In [4]:
import numpy as np

arr = np.arange(1, 10).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* Exercise 4 : Creating Multi-Dimensional Array With Random Numbers

In [5]:
import numpy as np

arr = np.random.rand(4, 5)
print(arr)
print(np.round(arr, 2))

[[0.73635558 0.58319267 0.41326925 0.36276256 0.76887082]
 [0.68118686 0.26953421 0.3738832  0.44392732 0.12988054]
 [0.37612904 0.59816769 0.3347173  0.11996871 0.29905037]
 [0.6965839  0.93043324 0.60723552 0.86514319 0.74878467]]
[[0.74 0.58 0.41 0.36 0.77]
 [0.68 0.27 0.37 0.44 0.13]
 [0.38 0.6  0.33 0.12 0.3 ]
 [0.7  0.93 0.61 0.87 0.75]]


* Exercise 5 : Indexing Arrays

In [9]:
import numpy as np

array = np.array([[21,22,23,22,22],
                  [20,21,22,23,24],
                  [21,22,23,22,22]])

second_row = array[1, :]  # Selects the second row (index 1)
print(second_row)

[20 21 22 23 24]


* Exercise 6 : Reversing Elements

In [7]:
import numpy as np

arr = np.arange(10)
reversed_arr = arr[::-1]  # or use np.flip(arr)
print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


* Exercise 7 : Identity Matrix

In [8]:
import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


* Exercise 8 : Simple Aggregate Funcs 

In [10]:
import numpy as np

arr = np.arange(10)  # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
total = np.sum(arr)
average = np.mean(arr)

print(f"Sum: {total}, Average: {average}")

Sum: 45, Average: 4.5


* Exercise 9 : Create Array And Change Its Structure

In [11]:
import numpy as np

arr = np.arange(1, 21).reshape(4, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


* Exercise 10 : Conditional Selection Of Values

In [13]:
import numpy as np

arr = np.arange(1, 21).reshape(4, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
